languageCode: "ja-JP"
baseUrl: ""
title: "にくたま雑記帳 - 自分のための備忘録"
theme: "anubis"
paginate: 10
# disqusShortname: yourdiscussshortname
# googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

permalinks:
  posts: /:year/:month/:day/:slug/

params:
  author: "にくたま雑記帳"
  description: ""
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
