languageCode: "ja-JP"
baseUrl: "/"
title: "にくたま雑記帳 - 自分のための備忘録"
theme: "anubis"
paginate: 10
# disqusShortname: yourdiscussshortname
googleAnalytics: G-TE9E7VBLBD
enableRobotsTXT: true
hasCJKLanguage: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

permalinks:
  posts: /:year/:month/:day/:slug/

params:
  author: "にくたま雑記帳"
  description: ""
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
